<x-guest-layout>
    <div><p class="text-sm font-bold uppercase tracking-[.18em] text-teal-700">Akses Terpadu</p><h1 class="mt-2 text-3xl font-extrabold tracking-tight text-slate-950">Selamat datang</h1><p class="mt-2 text-sm leading-6 text-slate-600">Gunakan email admin atau nomor WhatsApp jamaah. Sistem akan mengarahkan Anda secara otomatis.</p></div>
    <x-auth-session-status class="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700" :status="session('status')" />
    <form method="POST" action="{{ route('login') }}" class="mt-7" x-data="{ showPassword: false, loading: false }" @submit="loading = true">@csrf
        <label for="identity" class="block"><span class="mb-2 block text-sm font-bold text-slate-800">Email atau Nomor WhatsApp</span><div class="relative"><i data-lucide="user-round" class="pointer-events-none absolute left-4 top-1/2 size-4.5 -translate-y-1/2 text-slate-400"></i><input id="identity" name="identity" value="{{ old('identity') }}" required autofocus autocomplete="username" placeholder="admin@travel.com atau 0812..." class="control-field w-full py-3 pl-11 pr-4"></div><x-input-error :messages="$errors->get('identity')" class="mt-2" /></label>
        <div class="mt-5"><div class="mb-2 flex items-center justify-between"><label for="password" class="text-sm font-bold text-slate-800">Password</label>@if (Route::has('password.request'))<a href="{{ route('password.request') }}" class="text-xs font-bold text-blue-600 hover:text-blue-700">Lupa password admin?</a>@endif</div><div class="relative"><i data-lucide="lock-keyhole" class="pointer-events-none absolute left-4 top-1/2 size-4.5 -translate-y-1/2 text-slate-400"></i><input id="password" :type="showPassword ? 'text' : 'password'" name="password" required autocomplete="current-password" placeholder="Masukkan password" class="control-field w-full py-3 pl-11 pr-12"><button type="button" @click="showPassword = !showPassword" class="absolute right-2 top-1/2 grid size-9 -translate-y-1/2 place-items-center rounded-lg text-slate-400 hover:bg-slate-100" :aria-label="showPassword ? 'Sembunyikan password' : 'Tampilkan password'"><span x-show="!showPassword"><i data-lucide="eye" class="size-4.5"></i></span><span x-cloak x-show="showPassword"><i data-lucide="eye-off" class="size-4.5"></i></span></button></div><x-input-error :messages="$errors->get('password')" class="mt-2" /></div>
        <label class="mt-5 inline-flex cursor-pointer items-center gap-2 text-sm text-slate-600"><input type="checkbox" name="remember" class="size-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"><span>Ingat saya di perangkat ini</span></label>
        <button class="button-primary mt-6 w-full py-3" :disabled="loading"><span x-show="!loading">Masuk ke Sistem</span><span x-cloak x-show="loading" class="inline-flex items-center gap-2"><span class="size-4 animate-spin rounded-full border-2 border-white/35 border-t-white"></span>Memeriksa akun...</span></button>
    </form>
    <div class="mt-6 border-t border-slate-100 pt-5 text-center"><p class="text-sm text-slate-600">Belum punya akun jamaah?</p><a href="{{ route('portal.register') }}" class="mt-2 inline-flex text-sm font-extrabold text-teal-700 hover:text-teal-800">Buat akun jamaah →</a></div>
</x-guest-layout>
