<!DOCTYPE html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Buat Akun Jamaah</title><link rel="preconnect" href="https://fonts.bunny.net"><link href="https://fonts.bunny.net/css?family=figtree:400,500,600,700,800&display=swap" rel="stylesheet">@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-[#061321] font-sans text-slate-900 antialiased">
<main class="grid min-h-screen lg:grid-cols-[.9fr_1.1fr]">
    <section class="relative hidden overflow-hidden p-12 text-white lg:flex lg:flex-col lg:justify-between"><div class="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(20,184,166,.3),transparent_32%),radial-gradient(circle_at_80%_80%,rgba(37,99,235,.25),transparent_30%)]"></div><a href="{{ route('landing') }}" class="relative flex items-center gap-3"><img src="{{ asset('images/mantau-umroh-icon-dark.png') }}" class="size-12 rounded-2xl" alt="Logo"><span class="text-xl font-extrabold">{{ config('app.name', 'Mantau Umroh') }}</span></a><div class="relative max-w-xl"><p class="text-sm font-bold uppercase tracking-[.2em] text-teal-300">Portal Jamaah</p><h1 class="mt-4 text-5xl font-extrabold leading-tight">Mulai perjalanan ibadah dari satu akun.</h1><p class="mt-5 text-lg leading-8 text-slate-300">Setelah akun dibuat, Anda dapat membandingkan paket, mengisi biodata, dan memantau status pendaftaran.</p></div><p class="relative text-sm text-slate-500">Data Anda hanya digunakan untuk proses perjalanan umroh.</p></section>
    <section class="grid place-items-center bg-slate-50 px-5 py-10"><div class="w-full max-w-xl"><a href="{{ route('landing') }}" class="mb-7 inline-flex items-center gap-3 lg:hidden"><img src="{{ asset('images/mantau-umroh-icon-light.png') }}" class="size-11 rounded-xl" alt="Logo"><span class="font-extrabold">{{ config('app.name', 'Mantau Umroh') }}</span></a><div class="travel-panel p-6 sm:p-8"><p class="text-sm font-bold uppercase tracking-[.18em] text-teal-700">Langkah awal</p><h1 class="mt-2 text-3xl font-extrabold">Buat Akun Jamaah</h1><p class="mt-2 text-sm leading-6 text-slate-600">Biodata lengkap baru diminta setelah Anda memilih paket.</p>
        <form method="POST" action="{{ route('portal.register.store') }}" class="mt-7 grid gap-5">@csrf
            <label><span class="mb-1.5 block text-sm font-bold">Nama</span><input required name="name" value="{{ old('name') }}" autocomplete="name" class="control-field w-full" placeholder="Nama sesuai identitas"></label>
            <label><span class="mb-1.5 block text-sm font-bold">Nomor WhatsApp</span><input required name="phone" value="{{ old('phone') }}" inputmode="tel" autocomplete="tel" class="control-field w-full" placeholder="Contoh: 081234567890"></label>
            <label><span class="mb-1.5 block text-sm font-bold">Email <span class="font-normal text-slate-400">(opsional)</span></span><input type="email" name="email" value="{{ old('email') }}" autocomplete="email" class="control-field w-full" placeholder="nama@email.com"></label>
            <div class="grid gap-4 sm:grid-cols-2"><label><span class="mb-1.5 block text-sm font-bold">Password</span><input required type="password" name="password" autocomplete="new-password" class="control-field w-full"></label><label><span class="mb-1.5 block text-sm font-bold">Ulangi Password</span><input required type="password" name="password_confirmation" autocomplete="new-password" class="control-field w-full"></label></div>
            <label class="flex items-start gap-3 text-sm leading-6 text-slate-600"><input required type="checkbox" name="terms" value="1" class="mt-1 rounded border-slate-300 text-teal-600"><span>Saya menyetujui penggunaan data untuk proses pendaftaran dan pelayanan perjalanan umroh.</span></label>
            @if ($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700">{{ $errors->first() }}</div>@endif
            <button class="button-primary w-full">Buat Akun & Lihat Paket</button>
        </form><p class="mt-6 text-center text-sm text-slate-600">Sudah punya akun? <a href="{{ route('login') }}" class="font-extrabold text-teal-700">Masuk di sini</a></p></div></div></section>
</main></body></html>
