@extends('portal.layout')
@section('title', 'Lengkapi Biodata')
@section('content')
    <div class="mx-auto max-w-4xl">
        <div class="mb-6 grid grid-cols-3 gap-2 text-xs font-bold sm:text-sm"><div class="rounded-2xl bg-emerald-50 px-3 py-3 text-emerald-700">✓ Akun Dibuat</div><div class="rounded-2xl bg-emerald-50 px-3 py-3 text-emerald-700">✓ Paket Dipilih</div><div class="rounded-2xl bg-teal-600 px-3 py-3 text-white">3 Isi Biodata</div></div>
        <section class="mb-5 rounded-2xl border border-teal-200 bg-teal-50 p-5"><p class="text-xs font-bold uppercase tracking-[.14em] text-teal-700">Paket Pilihan</p><div class="mt-2 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-xl font-extrabold">{{ $package->program_name }}</h2><p class="mt-1 text-sm text-slate-600">{{ $package->branch?->name }} · {{ $package->departure_date->translatedFormat('d M Y') }}</p></div><a href="{{ route('portal.packages.index') }}" class="text-sm font-bold text-teal-700">Ganti paket</a></div></section>
        <section class="travel-panel overflow-hidden"><div class="border-b border-slate-200 p-6 sm:p-8"><p class="text-sm font-bold uppercase tracking-[.18em] text-teal-700">Data Pendaftaran</p><h1 class="mt-2 text-3xl font-extrabold">Lengkapi Biodata Jamaah</h1><p class="mt-2 leading-7 text-slate-600">Pastikan data sesuai KTP dan paspor. Admin cabang akan memverifikasinya sebelum pembayaran.</p></div>
            <form method="POST" action="{{ route('portal.biodata.store') }}" class="grid gap-5 p-6 sm:grid-cols-2 sm:p-8">@csrf
                <label class="sm:col-span-2"><span class="mb-1.5 block text-sm font-bold">Nama Lengkap sesuai Identitas</span><input required name="full_name" value="{{ old('full_name', auth()->user()->name) }}" class="control-field w-full"></label>
                <label><span class="mb-1.5 block text-sm font-bold">NIK</span><input required name="nik" value="{{ old('nik') }}" inputmode="numeric" class="control-field w-full" maxlength="20"></label>
                <label><span class="mb-1.5 block text-sm font-bold">Jenis Kelamin</span><select required name="gender" class="control-field w-full"><option value="">Pilih</option><option value="male" @selected(old('gender') === 'male')>Laki-laki</option><option value="female" @selected(old('gender') === 'female')>Perempuan</option></select></label>
                <label><span class="mb-1.5 block text-sm font-bold">Tanggal Lahir</span><input required type="date" name="birth_date" value="{{ old('birth_date') }}" class="control-field w-full"></label>
                <label><span class="mb-1.5 block text-sm font-bold">Nomor WhatsApp Akun</span><input disabled value="{{ $account->phone }}" class="control-field w-full bg-slate-100"></label>
                <label><span class="mb-1.5 block text-sm font-bold">Nomor Paspor <span class="font-normal text-slate-400">(opsional)</span></span><input name="passport_number" value="{{ old('passport_number') }}" class="control-field w-full"></label>
                <label><span class="mb-1.5 block text-sm font-bold">Masa Berlaku Paspor</span><input type="date" name="passport_expired_at" value="{{ old('passport_expired_at') }}" class="control-field w-full"></label>
                <label class="sm:col-span-2"><span class="mb-1.5 block text-sm font-bold">Alamat Lengkap</span><textarea required name="address" rows="3" class="control-field w-full">{{ old('address') }}</textarea></label>
                <div class="sm:col-span-2 border-t border-slate-200 pt-5"><h2 class="font-extrabold">Kontak Darurat</h2><p class="mt-1 text-sm text-slate-500">Keluarga yang dapat dihubungi selama perjalanan.</p></div>
                <label><span class="mb-1.5 block text-sm font-bold">Nama Kontak Darurat</span><input required name="emergency_contact_name" value="{{ old('emergency_contact_name') }}" class="control-field w-full"></label>
                <label><span class="mb-1.5 block text-sm font-bold">Nomor Kontak Darurat</span><input required name="emergency_contact_phone" value="{{ old('emergency_contact_phone') }}" inputmode="tel" class="control-field w-full"></label>
                <label class="sm:col-span-2"><span class="mb-1.5 block text-sm font-bold">Catatan Kebutuhan Khusus <span class="font-normal text-slate-400">(opsional)</span></span><textarea name="notes" rows="3" class="control-field w-full" placeholder="Contoh: kondisi kesehatan, kursi roda, atau kebutuhan pendampingan">{{ old('notes') }}</textarea></label>
                <label class="sm:col-span-2 flex items-start gap-3 rounded-2xl bg-slate-50 p-4 text-sm leading-6 text-slate-600"><input required type="checkbox" name="confirmation" value="1" class="mt-1 rounded border-slate-300 text-teal-600"><span>Saya menyatakan data yang diisi benar dan memahami bahwa pembayaran dilakukan langsung melalui kantor cabang travel.</span></label>
                @if ($errors->any())<div class="sm:col-span-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700">{{ $errors->first() }}</div>@endif
                <div class="sm:col-span-2 flex flex-col-reverse gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:justify-end"><a href="{{ route('portal.packages.show', $package) }}" class="button-secondary">Kembali</a><button class="button-primary px-7">Kirim Pendaftaran</button></div>
            </form>
        </section>
    </div>
@endsection
